### ISSUE TITLE
Templates section (request)

### ISSUE THREAD

**Issue by dmitrykurmanov** [sveltejs/integrations#19]
Hello! Thanks for your work!

I think it would be greate to add "templates" or "build templates" section or something like that.

For example, here a my component(library) template based on Svelte3, Rollup and Ava : https://github.com/dmitrykurmanov/svelte3-component-template

**Comment by antony** [comment]
@dmitrykurmanov looks good - would you mind opening a PR for this? Alternately if your template is no longer maintained, please feel free to close this issue.

**Comment by dmitrykurmanov** [comment]
Hello @antony ! I've found a better one https://github.com/YogliB/svelte-component-template

**Comment by dmitrykurmanov** [comment]
here the PR https://github.com/sveltejs/integrations/pull/36

**Comment by antony** [comment]
thanks!
