### ISSUE TITLE
Move non-integration stuff into a new repo

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/integrations#21]
As discussed in https://github.com/sveltejs/svelte/pull/2436, we're retiring this repo in favour of sveltejs/integrations (in fact I've renamed the repo so that it redirects).

Some of the things listed in the current README don't really belong in an integrations list, so will eventually need a new home. README snapshot right now (since I'm about to wipe it): https://github.com/sveltejs/svelte/pull/2436

**Comment by YogliB** [comment]
Something like [awesome-svelte](https://github.com/CalvinWalzel/awesome-svelte)?

It's not as maintained as I'd like, but I think it can do the job.

**Comment by ryanatkn** [comment]
I've been maintaining [a list of resources](https://github.com/ryanatkn/awesome-svelte-resources) similar to CalvinWalzel/awesome-svelte. I've been trying to avoid duplicating this official list and link to it in multiple places, but there's overlap where the official list is incomplete, like preprocessors. I [plan to deprecate](https://github.com/ryanatkn/awesome-svelte-resources/issues/18) it once there's an official replacement and welcome any feedback.

**Comment by pngwn** [comment]
@ryanatkn @calvinWalzel @wolfr

How would you feel about helping to maintain an official 'resources' list like the ones you already have but under the Svelte banner? It shouldn't be too much work and we don't know what that will look like or how it would work right now, but having a single canonical list of community resources or an at-a-glance view of the Svelte ecosystem that we can link to from the docs (or it could even be a page on the site) would probably help a lot of folks out.

**Comment by pngwn** [comment]
Okay, I've just seen the conversation with @sw-yx  in [this issue](https://github.com/ryanatkn/awesome-svelte-resources/issues/18), we'll have to think about whether or not a resource list should live with the `community` stuff.

**Comment by ryanatkn** [comment]
I'm interested in helping. I'll start by converting what I have to JSON and displaying it in a fork of sveltejs/community. From there it could be merged back or kept as a separate site, whichever gets chosen.

**Comment by pngwn** [comment]
A true legend.

**Comment by sw-yx** [comment]
@ryanatkn fwiw i think json is annoying to write and maintain. i prefer keeping it in markdown or keeping in yml.

**Comment by ryanatkn** [comment]
@sw-yx Yeah I agree about JSON. My plan is to get my markdown file into JSON, and then we can convert it to yml or something else, and also settle on a good format and merge with the other 2 lists. I think we'll want JSON at runtime but authoring in yml sounds good to me unless someone else has a suggestion. Gatsby uses yml for this purpose - https://github.com/gatsbyjs/gatsby/blob/master/docs/starters.yml

**Comment by sw-yx** [comment]
yeah. someone just PR'ed a new event and it's already invalid JSON lol (cos of trailing comma)


i'm setting up netlifycms for this here https://github.com/sveltejs/community/pull/5 and it should be able to consume and output and edit yml with a nice UI with no running server. can convert yml to json at runtime easily.

**Comment by Wolfr** [comment]
@pngwn I would feel totally fine if my list ([here](https://gist.github.com/Wolfr/21c126018f38ddb2b03070f11ba9b40b)) was re-used under an official community banner.

At the moment I can't promise much involvement but don't want to be a blocker, so feel free to just take it, edit it, re-use it.

**Comment by pngwn** [comment]
That’s great, thanks! It is an excellent resource.

**Comment by antony** [comment]
Closing this with a view to consolidate a proper component marketplace / browser under community in the near future.
