### ISSUE TITLE
Svelte Bazel TS

### ISSUE THREAD

**Issue by marcus-sa** [sveltejs/integrations#28]
Hey there!
I'm the author of https://github.com/avantci/svelte-ts which integrates TypeScript *(and type checking)* & Bazel support for Svelte.

It's not a bundler plugin nor a preprocessor, so is it possible to create a 3rd topic for a tool like this?

**Comment by antony** [comment]
Apologies for the delay in getting back to you. Please open a PR with the new section and a link to your tool and we'll get it merged!

**Comment by antony** [comment]
I've merged what I can, please feel free to update as required.
