### ISSUE TITLE
Add svelte-pwa starte template

### ISSUE THREAD

**Issue by tretapey** [sveltejs/integrations#42]
I have created a template based in the svelte starter template with pwa support: https://github.com/tretapey/svelte-pwa

Not sure if it works as an integration or not.

**Comment by antony** [comment]
Seems reasonable. Can you open a PR for it please? :)

**Comment by tretapey** [comment]
Sure, will do!

**Comment by antony** [comment]
Oh I meant open a PR to add it here, not on the main template.

It's a nice idea but Sapper is our PWA offering, so it's unlikely we'd want to start enabling PWA support on the basic template too.

**Comment by tretapey** [comment]
:O, I see, ok will do, thanks for clarifying

**Comment by tretapey** [comment]
PR created https://github.com/sveltejs/integrations/pull/43

**Comment by antony** [comment]
Closed by #43 - thanks!
