### ISSUE TITLE
Add a list of projects that use Svelte under the hood

### ISSUE THREAD

**Issue by Wolfr** [sveltejs/integrations#49]
Not sure who to address here, but would you welcome a list of projects that use Svelte that are more like Sapper alternatives? And then we could list their respective templates?

Thinking about:

* [Elder.js](https://elderguide.com/tech/elderjs/)
* [Jungle](https://www.junglejs.org/)
* [Routify](https://routify.dev/)
* [Roxi](https://roxi.dev/)

**Comment by antony** [comment]
Absolutely! I think it's a great idea. A lot of people aren't aware of these alternatives and their strengths.

**Comment by benmccann** [comment]
I think it'd be a good idea to list these as well

I also think it'd be a good idea to try to combine a lot of the best ideas of all the frameworks into one framework :smile:  I started trying to put together an RFC for that on the routing side, but while writing that RFC realized that the way Sapper handles CSS is really different than everyone else which makes that harder, so ended up writing a CSS RFC first

**Comment by antony** [comment]
Yep, something I've also started a RFC on but obviously it's a yak shaving excersize which delves into css, deployment, bundling... You name it!

**Comment by Wolfr** [comment]
@kevmodrome came up with the idea. I now added links to the OP. Anyone know of any other projects that are kind of Sapper alternatives?

**Comment by benmccann** [comment]
Our plan is to archive this repo in favor of https://github.com/svelte-society/sveltesociety.dev, so that'd be the place to add anything
